number: '0123456789'
symbol: "!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
lang_char: 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz'
#lang_char: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
experiment_name: 'en_filtered'
train_data: 'all_data/en_train_filtered'
valid_data: 'all_data/en_val'
manualSeed: 1111
workers: 4
batch_size: 32 #32
num_iter: 300000
valInterval: 10000
saved_model: ''
#saved_model: 'saved_models/en_filtered/best_accuracy.pth'
#saved_model: 'saved_models/en_filtered/iter_12500.pth'
#saved_model: 'saved_models/en_filtered/english_g2.pth'
FT: False
optim: False # default is Adadelta
lr: 1.
beta1: 0.9
rho: 0.95
eps: 0.00000001
grad_clip: 5
#Data processing
select_data: 'en_train_filtered' # this is dataset folder in train_data
batch_ratio: '1' 
total_data_usage_ratio: 1.0
batch_max_length: 34 
imgH: 64
imgW: 600
rgb: False
sensitive: True
PAD: True
contrast_adjust: 0.0
# Changed data_filtering_off to True Aug 31 10:18pm
data_filtering_off: True

# Model Architecture
# Transformation could be 'None' or 'TPS'
Transformation: 'None'
# FeatureExtraction can be 'VGG' or 'RCNN' or 'ResNet'
FeatureExtraction: 'VGG'  # turned this to ResNet Oct 31, 2021
#FeatureExtraction: 'ResNet'
SequenceModeling: 'BiLSTM'
# Prediction can be 'CTC' or 'Attn'
Prediction: 'CTC'
num_fiducial: 20
input_channel: 1
output_channel: 256
hidden_size: 256
decode: 'greedy'
# are we doing a new guy?!
#new_prediction: False
new_prediction: True
freeze_FeatureFxtraction: False
freeze_SequenceModeling: False
